apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: web
spec:
  nodeSelector:
    hardware: gpu
  containers: #docker run -d --name-nginx nginx
  - name: nginx
    image: nginx
  tolerations:
  - key: "harware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"