apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: podaf
spec:
  containers: #docker run -d --name-nginx nginx
  - name: nginx
    image: nginx:stable-perl
---    
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    purpose: pod2af
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values: #label value of pod1
            - podaf
        topologyKey: topology.kubernetes.io/zone
  containers: #docker run -d --name-nginx nginx
  - name: nginx
    image: nginx:stable-perl