apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    aff : podaf
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: aff
            operator: In
            values: #label value of pod1
            - podaff
        topologyKey: topology.kubernetes.io/zone
  containers: #docker run -d --name-nginx nginx
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"