apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    purpose: podaf
spec:
  containers: # docker run -d --name-nginx nginx
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    purpose: pod2af
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - podaf # Match the label value of the first pod
        topologyKey: kubernetes.io/hostname
  containers: # docker run -d --name-nginx nginx
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    purpose: pod3af
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
             - key: purpose
               operator: In
               values:
               - podaf
        topologyKey: "kubernetes.io/hostname"
  containers: # docker run -d --name-nginx nginx
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    purpose: pod4af
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
             - key: purpose
               operator: In
               values:
               - podaf
        topologyKey: "kubernetes.io/hostname"
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - pod3af # Match the label value of the first pod
        topologyKey: kubernetes.io/hostname
  containers: # docker run -d --name-nginx nginx
  - name: nginx
    image: nginx:stable-perl